/**
 * Device Service
 * 
 * Handles device identification, registration, and management.
 */

import { getIdToken } from './auth.js';
import { firestoreSet, firestoreGet, firestoreUpdate } from './firestore.js';

// ============================================================================
// CONSTANTS
// ============================================================================

const DEVICE_ID_KEY = 'deviceId';

// ============================================================================
// PUBLIC API
// ============================================================================

/**
 * Get or create a unique device ID
 * @returns {Promise<string>} Device ID
 */
export async function getDeviceId() {
  const stored = await chrome.storage.local.get(DEVICE_ID_KEY);
  
  if (stored[DEVICE_ID_KEY]) {
    return stored[DEVICE_ID_KEY];
  }
  
  // Generate new device ID
  const deviceId = generateDeviceId();
  await chrome.storage.local.set({ [DEVICE_ID_KEY]: deviceId });
  
  return deviceId;
}

/**
 * Get device information (browser, OS, etc.)
 * @returns {Object} Device info
 */
export function getDeviceInfo() {
  const userAgent = navigator.userAgent;
  
  // Check for navigator.brave (Brave browser specific)
  // Need to check both ways as Service Worker may have limited access
  const hasBraveNavigator = typeof navigator.brave !== 'undefined';
  
  // Detect browser (order matters - check specific browsers before generic ones)
  let browser = 'unknown';
  if (userAgent.includes('Brave') || hasBraveNavigator) {
    browser = 'brave';
  } else if (userAgent.includes('OPR/') || userAgent.includes('Opera')) {
    browser = 'opera';
  } else if (userAgent.includes('Edg/')) {
    browser = 'edge';
  } else if (userAgent.includes('Vivaldi/')) {
    browser = 'vivaldi';
  } else if (userAgent.includes('Arc/')) {
    browser = 'arc';
  } else if (userAgent.includes('Chrome/')) {
    browser = 'chrome';
  } else if (userAgent.includes('Firefox/')) {
    browser = 'firefox';
  } else if (userAgent.includes('Safari/')) {
    browser = 'safari';
  }
  
  console.log('[Device] Detected browser:', browser, 'hasBraveNavigator:', hasBraveNavigator, 'userAgent:', userAgent.substring(0, 100));
  
  // Detect OS
  let os = 'unknown';
  if (userAgent.includes('Mac OS')) {
    os = 'macOS';
  } else if (userAgent.includes('Windows')) {
    os = 'Windows';
  } else if (userAgent.includes('Linux')) {
    os = 'Linux';
  } else if (userAgent.includes('Android')) {
    os = 'Android';
  } else if (userAgent.includes('iOS') || userAgent.includes('iPhone') || userAgent.includes('iPad')) {
    os = 'iOS';
  }
  
  // Get browser name for display
  const browserName = getBrowserName(browser);
  
  return {
    browser,
    os,
    browserName,
    userAgent,
  };
}

/**
 * Get display name for browser
 */
function getBrowserName(browser) {
  const browserNames = {
    brave: 'Brave',
    opera: 'Opera',
    edge: 'Edge',
    vivaldi: 'Vivaldi',
    arc: 'Arc',
    chrome: 'Chrome',
    firefox: 'Firefox',
    safari: 'Safari',
    unknown: 'Browser',
  };
  return browserNames[browser] || 'Browser';
}

/**
 * Generate default device name
 * @returns {string} Device name
 */
export function getDefaultDeviceName() {
  const info = getDeviceInfo();
  return `${info.browserName} - ${info.os}`;
}

/**
 * Register device in Firestore
 * @param {string} userId - User ID
 * @returns {Promise<Object>} Device document
 */
export async function registerDevice(userId) {
  const deviceId = await getDeviceId();
  const info = getDeviceInfo();
  
  // Check if device already exists
  const existingDevice = await firestoreGet(`users/${userId}/devices/${deviceId}`);
  
  const defaultName = getDefaultDeviceName();
  
  const deviceData = {
    browser: info.browser,
    os: info.os,
    lastSeen: new Date().toISOString(),
    isOnline: true,
  };
  
  if (!existingDevice) {
    // New device - set default name
    deviceData.name = defaultName;
    deviceData.createdAt = new Date().toISOString();
  } else {
    // Check if name matches current browser - fix mismatched names
    const expectedName = `${getBrowserName(info.browser)} - ${info.os}`;
    const nameMatchesBrowser = existingDevice.name === expectedName;
    
    // Update name if it doesn't match current browser (auto-generated name was wrong)
    // or if it was an auto-generated name from a different browser
    if (!nameMatchesBrowser) {
      // Check if current name looks like an auto-generated name (contains " - ")
      const looksAutoGenerated = existingDevice.name && existingDevice.name.includes(' - ');
      if (looksAutoGenerated) {
        deviceData.name = defaultName;
        console.log('[Device] Fixing device name from', existingDevice.name, 'to', defaultName);
      }
    }
  }
  
  await firestoreSet(`users/${userId}/devices/${deviceId}`, deviceData, !!existingDevice);
  
  return {
    id: deviceId,
    ...deviceData,
    name: existingDevice?.name || deviceData.name,
  };
}

/**
 * Update device online status
 * @param {string} userId - User ID
 * @param {boolean} isOnline - Online status
 */
export async function updateDeviceStatus(userId, isOnline) {
  const deviceId = await getDeviceId();
  
  await firestoreUpdate(`users/${userId}/devices/${deviceId}`, {
    isOnline,
    lastSeen: new Date().toISOString(),
  });
}

/**
 * Update device name
 * @param {string} userId - User ID
 * @param {string} name - New device name
 */
export async function updateDeviceName(userId, name) {
  const deviceId = await getDeviceId();
  
  await firestoreUpdate(`users/${userId}/devices/${deviceId}`, { name });
}

/**
 * Get all devices for a user
 * @param {string} userId - User ID
 * @returns {Promise<Array>} List of devices
 */
export async function getDevices(userId) {
  const deviceId = await getDeviceId();
  
  // This will be implemented in firestore.js with collection query
  const { firestoreList } = await import('./firestore.js');
  const devices = await firestoreList(`users/${userId}/devices`);
  
  // Mark current device
  return devices.map(device => ({
    ...device,
    isCurrentDevice: device.id === deviceId,
  }));
}

// ============================================================================
// PRIVATE HELPERS
// ============================================================================

/**
 * Generate a unique device ID
 */
function generateDeviceId() {
  const timestamp = Date.now().toString(36);
  const randomPart = Math.random().toString(36).substring(2, 10);
  return `${timestamp}-${randomPart}`;
}
